# Conclusion

The present study aimed to achieve a comprehensive analysis of the renewable energy research capacity in Africa. Although renewable energy research is a fairly broad topic and solely relying on scientometric research cannot cover all of its aspects, the study results yielded some important observations about the general situation of RE research capacity in African countries.

The number of RE-related publications is increasing in every region of Africa. Although Northern and Southern Africa publishing the biggest part of the total of RE-related publications in Africa, lots of countries from Western, Central and Eastern Africa are increasing their output rapidly.

African regions seem to be fairly well interconnected in their individual regions and several of them show a considerable amount of co-publications with intercontinental partners. However, in general, there is a lack of interregional collaboration in the African continent. Only some of the most visible countries appear in other regions as one of the most visible collaborators. In relation, a number of African countries also tend to collaborate with a specific cluster of intercontinental partners with very little diversity.

The content of the RE-related publications in Africa displays a strong emphasis especially on solar energy related science and technology in recent years followed by wind energy and biomass related topics. Furthermore, African academic organisations also increasingly research geographical specifications of their regions that could be beneficial for a specific kind of RE approach.

The analysis of the trending research areas in the most visible organisations also displayed that in the last couple of years there is a sudden decline in the most visible research areas in terms of yearly publications (e.g. Energy & Fuels). Simultaneously, there are a few previously less visible research areas that are rapidly growing in numbers. Questions like if there is a real shift in RE-related research away from previously dominant areas or if specific topics are categorised under other disciplines than before, furthermore, if this transition indicates that the same cluster of academicians is now working in other disciplines or if the academicians working in previously dominant research areas abandoning RE-related research and vice versa are questions to be answered with further research.

 